[project]
name = "fastapi-dynamodb-sample"
version = "0.1.0"
description = "A sample FastAPI project with DynamoDB"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.35.80",
    "fastapi[standard]>=0.115.6",
]

